# Generated by Django 4.0.1 on 2022-01-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=500, verbose_name='Identificação')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation', verbose_name='Alojamento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sector', verbose_name='Setor')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shed', verbose_name='Galpão')),
            ],
            options={
                'verbose_name': 'Temperatura',
                'verbose_name_plural': 'Temperaturas',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=500, verbose_name='Identificação')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('data', models.JSONField(verbose_name='Valor')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation', verbose_name='Alojamento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sector', verbose_name='Setor')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shed', verbose_name='Galpão')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=500, verbose_name='Identificação')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation', verbose_name='Alojamento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sector', verbose_name='Setor')),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shed', verbose_name='Galpão')),
            ],
            options={
                'verbose_name': 'Umidade',
                'verbose_name_plural': 'Umidades',
            },
        ),
    ]
